use_frameworks!

platform :ios, '9.0'

target 'LYExtension_Example' do
  
  pod 'LYComponent', :path => '../'

#  target 'LYExtension_Example' do
    inherit! :search_paths

    
#  end
  
  target 'LYExtension_Tests' do
    inherit! :search_paths

    
  end
end
